version = '2'

[run]
go = '1.24'
tests = true

[linters]
enable = [
  'containedctx',
  'contextcheck',
  'decorder',
  'errname',
  'errorlint',
  'staticcheck',
  'whitespace'
]

[linters.exclusions]
generated = 'lax'
presets = [
  'comments',
  'common-false-positives',
  'legacy',
  'std-error-handling'
]
paths = [
  'third_party$',
  'builtin$',
  'examples$'
]

[formatters]
enable = [
  'gofmt',
  'gofumpt'
]

[formatters.exclusions]
generated = 'lax'
paths = [
  'third_party$',
  'builtin$',
  'examples$'
]

[linters.exclusions.rules]
path = "examples/(.+)\\.go"
linters = ["unused"]